### ISSUE TITLE
Failure to success checkbox error

### ISSUE THREAD

**Issue by michellexliu** [nyc-cto/feedback-module#54]
**Bug Description**
When the user forgets to check a checkbox before submitting, then checks a box and submits again while the request service is down, then re-checks a box and submits again when the services are back up, the submission doesn't go through

**To Reproduce**
1. Change the `.post` endpoint in `requestServices` to an intentionally incorrect one.
2. On the "I couldn't find what I was looking for" page, click submit.
3. Click on a checkbox
4. Click submit again (behavior: by now, will have 2 errors— checkbox error & feedback couldn't be submitted error, checkbox gets unchecked)
5. Click a checkbox again
5. Change the endpoint in `requestServices` to a correct one
7. Press submit again

**Comment by ksiegel1923** [comment]
Not actually a bug. Something we should test in the actual endpoint
